version: "3.4"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "accounts"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "accounts"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  account-service:
    image: ahmedmq/account-svc
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/accounts"
      SPRING_DATASOURCE_USERNAME: "accounts"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_RABBITMQ_HOST: "rabbitmq"
    depends_on:
      - postgres
      - rabbitmq